spring:
  datasource:
    url: jdbc:mysql://mysql-container:3306/product_catalog_service
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  zipkin:
    base-url: http://zipkin-server:9411
  application:
    name: product-catalog-service

logging:
  file:
    path: /Users/zhenluo/Downloads/logs/microservice.log

management:
  zipkin:
    enabled: true
  tracing:
    enabled: true
    sampling:
      probability: 1.0
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
server:
  port: 8081
